name: Build FAQ
permissions:
  contents: write
concurrency:
  # Ensure only a single instance of this workflow runs at a time
  group: ${{ github.workflow }}

on:
  schedule:
  - cron: '13 0-17,22-23 * * *'
  workflow_dispatch:

jobs:
  build-faq:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout analyser repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build FAQ
        env:
          GEMINI_API_KEY: ${{ secrets.gemini_api_key_faq }}
        run: npm exec tsx -- bin/build-faq.ts

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add:              ./data
          message:          'Updated draft FAQ'
          default_author:   github_actions